### ISSUE TITLE
Revision edits checklist

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#231]
- [x] Please limit the revised manuscript to no more than 6000 words, excluding acknowledgments, references and figure legends, which should be shortened as much as possible.
- [x] Figures: You are allowed up to 6 main-text figures or tables. Figure and table legends should be concise. We discourage the use of red/green for contrast. Please follow our figure guidelines, [found here](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fdocuments%2FNRJs-guide-to-preparing-final-artwork.pdf&data=05%7C01%7Ccasey.s.greene%40cuanschutz.edu%7Cc08d879944fb4cfe4f3108db09879c60%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638114250677626824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l9zUM4OzjETILZhYtNsynPspGhyHFcUMb9iPWPjhw0A%3D&reserved=0). Please upload figures individually, with editable layers intact. AI, EPS, PDF files preferred.
- [x] limit the number of references to 100
- [x] identify those references (≤ 10% of the total) that, in your opinion, represent key contributions to the field. Please add a short note (1–2 sentences) at the end of each of these references, explaining their importance. Only papers that have been published or accepted by a named publication or recognized preprint server should be in the numbered list.
- [x] Check for citation of unpublished work. Unpublished meeting abstracts, personal communications and manuscripts under consideration (and not formally accepted) may be cited only in the main text.
- [x] If you are including any Supplementary Information, please complete and return [this inventory document](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.nature.com%2Fdocuments%2FInventory_of_Supporting_Information_2021.docx&data=05%7C01%7Ccasey.s.greene%40cuanschutz.edu%7Cc08d879944fb4cfe4f3108db09879c60%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638114250677626824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T3cInTNMoYiiq8q0YSY7rZoriA1L9YG3SDJL4HZ6JZA%3D&reserved=0) with your final submission files. Instructions for organizing the Supplementary Information are also included in this document.
- [x] Competing Interests:
In the interests of transparency and to help readers to detect potential bias, Nature and the Nature monthly research journals now require all authors to declare any potential competing financial interests in relation to papers accepted for publication. This statement will be published after the acknowledgments section of your article. Please ensure that the information in the "Competing Financial Interests" section of the manuscript data online is correct and that any competing interests described there are also listed in a paragraph at the end of your manuscript. This will appear as a web supplement. More detailed information about this policy and the form can be found on the web at [http://www.nature.com/authors/editorial_policies/competing.html](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.nature.com%2Fauthors%2Feditorial_policies%2Fcompeting.html%253C%2Fa%253E&data=05%7C01%7Ccasey.s.greene%40cuanschutz.edu%7Cc08d879944fb4cfe4f3108db09879c60%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638114250677783063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ae7VsjLLCdv3ZjT87GyCxrBFz%2FNdkDabghtr2lwllYs%3D&reserved=0) and in a 2006 editorial [http://www.nature.com/nmeth/journal/v3/n11/full/nmeth1106-869.html](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.nature.com%2Fnmeth%2Fjournal%2Fv3%2Fn11%2Ffull%2Fnmeth1106-869.html%253C%2Fa%253E.&data=05%7C01%7Ccasey.s.greene%40cuanschutz.edu%7Cc08d879944fb4cfe4f3108db09879c60%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638114250677783063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XbtKcXtaf%2F4hFpEUhpi3qpaJfH%2F5yUIaSwDhriuO9tI%3D&reserved=0).
- [x] consult with your coauthors to ensure that all names, affiliations, and titles are represented correctly
- [x] Acknowledgements and Contributions:
Acknowledgements :
• Refer to individuals by first initial and last name, without titles or affiliations
• If any listed authors received grants or funding then that information must be provided. Please list each grant number, followed by the initials of the author who received it, in the Acknowledgements section of your paper.
Contributions: If there is more than one author:
• Please keep your Author Contributions statement as concise as possible
• Specify the individual contributions of each coauthor.
Example: "A.P.M. contributed Y and Z; B.T.R. contributed Y and W,” etc.
• Please ensure that author initials listed match the author list
• Distinguish authors with the same initials in some way
Example: “J. Doe contributed Y and Z; J. Dee contributed Y and W,” etc.
- [x] Manuscript Order
All manuscripts must include the following sections, ordered as listed:
• Title
• Author List and affiliations (including present addresses, equal contributions statement, and corresponding author email(s))
• Abstract (150 words, no references)
• Main Text (with subheadings)
• Data and Code Availability Statement (if applicable)
• Acknowledgements
• Author Contributions (if there is more than one author)
• Ethics Declaration
• References (for main text only)
• Figure legends (for main text only)
• Tables (note: tables should be pasted into Word files as editable tables, not as images)
• Boxes

**Comment by jaybee84** [comment]
Additional edits: 
- [x] a box listing the most common "tasks" for ML in the context of rare diseases and refer back to them throughout the main text
- [x] refer to this body of work and state what type of methodology has been excluded from the review (here are example PMIDs from the rare disease genetic association literature: 26924528, 21737059, 25502226, 28669401).
